125-show-alert-for-non-handled-files
graasp/graasp-mobile-builder pull request #171
Opened 2024-02-12 22:45 UTC by alvrba

2024-02-13 07:19 UTC, spaenleh requested changes
I think we can include contact information to request support of a type.

Also tests ? 👀

2024-02-13 07:19 UTC, spaenleh commented on src/components/ItemUnsupported.tsx
> +      </Text>
Maybe we can add a suggestion to contact us in order to request support for some file types ? This way we can reduce frustration and learn what we need to implement in priority.

2024-02-13 07:19 UTC, spaenleh commented on src/components/ItemUnsupported.tsx
> +        {t('This file cannot be opened in the mobile app')}
Maybe display the item type here so we know what we need to support. 
I think `file` may not be the right wording. I would suggest using `element` instead, as they can be interactive elements (h5p, etherpads etc) and not strictly files.

2024-02-15 14:48 UTC, alvrba commented
Pending to first update to Expo SDK 50 and then add Sentry to the project

2024-03-22 15:30 UTC, pyphilia requested changes

2024-03-22 15:30 UTC, pyphilia commented on src/components/ItemUnsupported.tsx
> +        {t('The element cannot be opened in the mobile app', {
```suggestion
        {t('The item cannot be opened in the mobile app', {
```

2024-03-22 15:30 UTC, pyphilia commented on src/components/ItemUnsupported.tsx
> +            name={'feedback'}
```suggestion
            name="feedback"
```

2024-03-22 15:30 UTC, pyphilia commented on src/langs/en.json
> +  "The element cannot be opened in the mobile app": "The {{type}} element cannot be opened in the mobile app",
```suggestion
  "The item cannot be opened in the mobile app": "The {{type}} item cannot be opened in the mobile app",
```

2024-03-22 15:30 UTC, pyphilia commented on src/langs/fr.json
> +  "The element cannot be opened in the mobile app": "Cet {{type}} élément ne peut pas être ouvert dans l'application mobile",
```suggestion
  "The element cannot be opened in the mobile app": "L'élément {{type}} ne peut pas être ouvert dans l'application mobile",
```

2024-03-22 15:30 UTC, pyphilia commented on src/langs/fr.json
> +  "I would like to be able to see this item": "J'aimerais pouvoir voir cet article"
```suggestion
  "I would like to be able to see this item": "J'aimerais pouvoir voir cet élément"
```
but anyway the message will change (cf comment above)

2024-03-22 15:30 UTC, pyphilia commented on src/components/ItemUnsupported.tsx
> +        title={t('I would like to be able to see this item')}
```suggestion
        title={t('Send a request to the development team to support itemtype', {type:item.type})}
```

2024-04-02 07:37 UTC, spaenleh commented on src/langs/fr.json
> +  "Send a request to the development team to support": "Envoyer une demande à l'équipe de développement pour soutenir {{type}}"
```suggestion
  "Send a request to the development team to support": "Envoyer une demande à l'équipe de développement pour supporter {{type}}"
```

2024-04-02 09:47 UTC, spaenleh approved these changes

2024-04-02 09:47 UTC, spaenleh commented on src/components/ItemUnsupported.tsx
> +            [{ text: t('Close'), onPress: () => console.debug('Close alert') }],
Is this debugging ?

2024-04-02 10:11 UTC, merged